### ISSUE TITLE
"No module named 'pytz'" but there is no pytz in the code

### ISSUE THREAD

**Issue by ViniciusARZ** [singer-io/tap-sendgrid#9]
Hello! I started to use the integration recently, and it worked fine, but out of the blue this error kept coming up when reading the `from singer import utils` module, and it broke the entire connection in Stitch. Any ideas on how to fix it? I reviewed the code and everything seems fine to me...

**Comment by kmartin-3bl** [comment]
Also encountering this issue trying to use the sendgrid tap in Stitch. Data extracts have been failing since at least December. @ViniciusARZ did you come to any resolution on your issue?

```
2023-01-31 17:42:33,524Z   main - INFO Running tap-sendgrid version 1.0.3 and target-stitch version 3.2.1
2023-01-31 17:42:34,683Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-sendgrid --config /tmp/tap_discover_config.json --discover
2023-01-31 17:42:34,729Z    tap - Traceback (most recent call last):
2023-01-31 17:42:34,730Z    tap -   File "/code/orchestrator/tap-env/bin/tap-sendgrid", line 33, in <module>
2023-01-31 17:42:34,730Z    tap -     sys.exit(load_entry_point('tap-sendgrid==1.0.3', 'console_scripts', 'tap-sendgrid')())
2023-01-31 17:42:34,730Z    tap -   File "/code/orchestrator/tap-env/bin/tap-sendgrid", line 25, in importlib_load_entry_point
2023-01-31 17:42:34,730Z    tap -     return next(matches).load()
2023-01-31 17:42:34,730Z    tap -   File "/root/.pyenv/versions/3.9.6/lib/python3.9/importlib/metadata.py", line 77, in load
2023-01-31 17:42:34,730Z    tap -     module = import_module(match.group('module'))
2023-01-31 17:42:34,730Z    tap -   File "/root/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-01-31 17:42:34,730Z    tap -     return _bootstrap._gcd_import(name[level:], package, level)
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-01-31 17:42:34,730Z    tap -   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-01-31 17:42:34,730Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_sendgrid/__init__.py", line 3, in <module>
2023-01-31 17:42:34,730Z    tap -     import singer
2023-01-31 17:42:34,730Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/__init__.py", line 1, in <module>
2023-01-31 17:42:34,731Z    tap -     from singer import utils
2023-01-31 17:42:34,731Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 8, in <module>
2023-01-31 17:42:34,731Z    tap -     import pytz
2023-01-31 17:42:34,731Z    tap - ModuleNotFoundError: No module named 'pytz'
2023-01-31 17:42:34,737Z   main - INFO Tap exited abnormally with status 1
2023-01-31 17:42:34,741Z   main - INFO No tunnel subprocess to tear down
2023-01-31 17:42:34,741Z   main - INFO Exit status is: Discovery failed with code 1.
````

**Comment by ldeboer** [comment]
I'm also having this same issue (trying to use the SendGrid tap in Stitch)

**Comment by NelisVerhoef** [comment]
I did a quick PR that I think will fix this issue. 

But looking at the activity for this tap, I don't expect anyone will review it any time soon. 

In any case, it lives [here](https://github.com/singer-io/tap-sendgrid/pull/10)

**Comment by NelisVerhoef** [comment]
Once I've started testing that change, I realised there were a couple of other issues because some of the older APIs have been deprecated. 

As such, I've started creating a new tap using the singer spec. 

I'll try to spend some time on it and get back to you if I end up finishing it.

**Comment by poningru** [comment]
Hello 
Was there any movement with this? Stitch is still clearly using the old tap: `2024-09-20 22:19:21,205Z   main - INFO Running tap-sendgrid version 1.0.3 and target-stitch version 3.2.1` Anyone have workarounds? Thanks

**Comment by RushiT0122** [comment]
Fixed in PR https://github.com/singer-io/tap-sendgrid/pull/13
